spring:
  profiles:
    active:
    - local

---


spring:
  profiles:
  - local

  mvc: 
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/healthcatch?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  session:
    jdbc:
      initialize-schema: always
      
      
  mail:
    host: smtp.naver.com
    port: 465
    username: 159@naver.com
    password: jomang3002!
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true
      
      
      
server:
 port: 8080
 tomcat:
    file-encoding: UTF-8
    
 servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
       
    jsp:
      init-parameters: 
        development: true 
    session: 
      timeout: 7200
 error:
      whitelabel:
        enabled: false 
mybatis:
  type-aliases-package: com.zikgu.example.domain
  mapper-locations: mapper/**/*.xml
  
  logging:
  config: classpath:logback-spring.xml  

